### ISSUE TITLE
Feat: Internal Currency System

### ISSUE THREAD

**Issue by Hemit99123** [Hemit99123/dailysat#36]
- created an in-game currency using web3 technologies
- this can be used to purchase cool nfts 
- have a graphic designer work on the nfts 
- use pre-existing blockchain technologies such as solana or ethereum

NOTE: technology used by the internal currency system is SUBJECT TO CHANGE

**Comment by LAKSHYAJAIN16** [comment]
amount of currency is saved in the DB.

no NFT art done yet

**Comment by Hemit99123** [comment]
amazing! nft art might cost some money through gas fees so leave that for now :)

**Comment by LAKSHYAJAIN16** [comment]
done
