### ISSUE TITLE
Create user authentication 

### ISSUE THREAD

**Issue by Hemit99123** [Hemit99123/dailysat#39]
The architecture: 

A) when the user logs in or signs up, we give them a custom JWT token. we save that token as a cookie. the token contains their user information + data and time of login.
B) we also save that token in mongoDB
C) when the user sends out an API Request we validate their token by checking if it's in the mongoDB collection (to check how long it's been since they've signed in)

If it's been more than like a day or something, we invalidate the token. this should be literally free.

**Comment by LAKSHYAJAIN16** [comment]
done

**Comment by Hemit99123** [comment]
thank you :) please provide an update through bullet points on this issue. this is for documentation purposes so any other devs and future devs can reference!
