### ISSUE TITLE
Fix: CSS ui fix from closed sidebars

### ISSUE THREAD

**Issue by Gabriel-Dalton** [Hemit99123/dailysat#44]
![image](https://github.com/user-attachments/assets/88800590-3f73-4e57-8fac-b08083205ade)

**Comment by Hemit99123** [comment]
thank you for the feedback @Gabriel-Dalton! Our team will work swiftly in improving the UI so it looks more desirable :)

**Comment by Hemit99123** [comment]
Finished, error was fixed successfully through above solution :)

**Comment by Hemit99123** [comment]
Again thank you for the feedback @Gabriel-Dalton
